### ISSUE TITLE
Functions Runtime not startet after deployment

### ISSUE THREAD

**Issue by Ingo67** [Azure/iotc-device-bridge#14]
![image](https://user-images.githubusercontent.com/42940989/49498325-f971b280-f86a-11e8-8eb0-ff9edcf38295.png)

**Comment by peolivei2** [comment]
Hi @Ingo67,

Did the runtime start after a while? It may be a transient issue.

We also pushed new changes to the solution last week, making consumption plan the default. If the issue is not solved yet, can you try deploying again to have the latest changes?

**Comment by Ingo67** [comment]
Hi

I am sorry that I did not mention.

Yes, after deinstallation and a new installation of the device bridge, I can start and use the device bridge.

Sorry for the delay.

Best regards

Ingo

Von: peolivei2 <notifications@github.com>
Gesendet: Montag, 10. Dezember 2018 20:58
An: Azure/iotc-device-bridge <iotc-device-bridge@noreply.github.com>
Cc: Ingo Schlalos <schlalos@swms.de>; Mention <mention@noreply.github.com>
Betreff: Re: [Azure/iotc-device-bridge] Functions Runtime not startet after deployment (#14)


Hi @Ingo67<https://github.com/Ingo67>,

Did the runtime start after a while? It may be a transient issue.

We also pushed new changes to the solution last week, making consumption plan the default. If the issue is not solved yet, can you try deploying again to have the latest changes?

**Comment by peolivei2** [comment]
Glad to know that the issue was solved.
