### ISSUE TITLE
TTN decoder function

### ISSUE THREAD

**Issue by coastalplain** [Azure/iotc-device-bridge#19]
I am trying to utilize the Azure IoT Central Device Bridge to send data from my node through TTN HTTP to azure.  The node creates a payload with the [arduino-lmic sflt16](https://github.com/mcci-catena/arduino-lmic#sflt16) encoding as described [here]( https://learn.adafruit.com/the-things-network-for-feather/arduino-code), which is obviously different from the recommended JavaScript provided in "Example 3:  Connecting devices from The Things Network through the device bridge."  

Can you point us to a recommendation or similar arduino library that can be used to encode the payload on the device prior to sending through the gateway to TTN for using the decoder in the example for TTN?  

The bridge appears to be working as when data arrives at TTN, there is an almost immediate response in my log at the IoTCIntegration function.  However, an error is posted:

> 2019-02-25T23:02:20.403 [Information] Executing 'Functions.IoTCIntegration' (Reason='This function was programmatically called via the host APIs.', Id=7d5390c8-0c64-4a2d-ba0e-6b5101286cea)
> 2019-02-25T23:02:20.413 [Information] [ERROR] Invalid format: deviceId must be alphanumeric, lowercase, and may contain hyphens.
> 2019-02-25T23:02:20.414 [Information] Executed 'Functions.IoTCIntegration' (Succeeded, Id=7d5390c8-0c64-4a2d-ba0e-6b5101286cea)

Thank you.

**Comment by firedog1024** [comment]
Hi, let me see if I can help you out here.

The issue with the name is that the device provisioning service is a little picky about characters in the deviceId (well actually it's very picky, but there is a fix coming to make it less so).  I'm guessing you either have invalid characters in the dev-id registered with TTN or possibly using the device EUI as the deviceId.  The deviceId needs to be lowercase letters, numbers, and can contain hyphens.  All other characters are considered invalid.

Inserting a context.log(req.body); line into the Azure Function will help in seeing what is getting sent over from TTN and help debug this.

Regarding decoding the message I looked at the links you provided and they have javascript decoding function code provided for each data type.  You could use those functions in the TTN payload decoder as they seem to work when I added them into mine for a quick check.  Then decode the byte array on the TTN side to form JSON to then send to the Azure Function on the Bridge.  Alternatively you could put the Javascript functions in the Azure Function code and do the decoding there to build the JSON payload to send to IoT Central.

Hopefully this helps, if not please reply back and we will try to help you get this working.  We also have some sample code in a repo here for Arduino, these are for the TTN Uno and Node devices but should be adaptable to other devices.  The repo can be found here: [https://github.com/firedog1024/TheThingsNetwork-with-Azure-IoT-Central](https://github.com/firedog1024/TheThingsNetwork-with-Azure-IoT-Central)

**Comment by coastalplain** [comment]
Thank you!  It does appear the Device EUI is being sent and decoded as the DeviceID (which is in the correct format with only lower case, numbers, hyphens, and no special characters.  
When I added the following to line 30 of the index.js of IoTCIntegration, 

>context.log(req.body)

 the following came through, which definitely adds up to the HEX for my Device EUI in the Device Overview Tab of this particular device  (I used *** to replace the last ten capitol letters and numbers:

>2019-02-26T20:10:59.334 [Information] [ERROR] Invalid format: deviceId must be alphanumeric, lowercase, and may contain hyphens.
>2019-02-26T20:10:59.334 [Information] { device: { deviceId: '00B39C**********' },
  measurements: { battVolt: 4.1839599609375, measure: 3210.44921875, state: 0 } }

It is nice to see them showing up at Azure!

Here is the screen shot of the Device EUI and the Device ID from TTN as seen on the Device Overview screen from TTN Console -> Application-> *** -> Devices ->ea-0004********:
![image](https://user-images.githubusercontent.com/8905768/53443762-644e0800-39da-11e9-8d15-3652c052d42f.png)

I'm not quite sure how to identify/parse the deviceId over the Device EUI in this case.  

If I move the decoder from TTN Custom Payload Format decoder, would this allow decoding of additional metadata (e.g. gateway, time, lat/long, altitude, etc.?).  Would moving the decoding would potentially reduce internet traffic?  Would it be more secure that way?   Also, in which file at what line would you recommend placing the decoder from TTN--are these just additional functions that would go into the index.js?

Thank you for your time

**Comment by coastalplain** [comment]
Issue solved. 

After identifying the full package of information being sent through the HTTP Integration on TTN, it appears that line 23 was requesting the "hardware_serial" which is by definition all caps and numbers.  By changing that line to "dev_id" the devices are properly identified and passed on to IoT Central.
![image](https://user-images.githubusercontent.com/8905768/53497739-d8d48580-3a72-11e9-964f-83bec6b9c444.png)

**Comment by peolivei2** [comment]
Glad to know that it works now. About the additional fields, here's a reference for the payload format that TTN sends `https://www.thethingsnetwork.org/docs/applications/http/`

We only use `payload_fields` as `measurements`, as you can see in line 25, but you can use any other field from `req.body` insise the `measurements` object. Just make sure that after the transformation, `measurements` is a flat object of field names to values, as expected by device-bridge.

**Comment by coastalplain** [comment]
Indeed!  The devices are now showing up in `AzureIoTCentral.com`, but it seems I still have to learn some more about the payloads and transformations, as the payload is not graphed (Missing Data at AzureIoTC; see second image below).  For each uplink received, the log receives an error:
` [Information] [ERROR] Data must be a string or a buffer`
even though the overall event succeeds (also to note is the difference in output structure between the two Devices in the log; one is a single line, the other multiple lines):
![image](https://user-images.githubusercontent.com/8905768/53524813-6f726800-3aae-11e9-9ed8-da1e2ef6786d.png)

Is this kind of `[ERROR]` caused by improper transformation or something else?  The data do not make it to `https://****.azureiotcentral.com/details/device` but obviously the existence of the Device is recognized from TTN through the bridge into azureIoTC (and it is being sent to blob storage, _e.g._ 13.avro):
![image](https://user-images.githubusercontent.com/8905768/53524553-adbb5780-3aad-11e9-99fb-8ca399126d15.png)

Also of note is that the payload value for `state ` should be either `0` or `1`, not float.  That is likely due to the decoder on TTN where I am decoding the payload from the Device using the same `function sflt162f(rawSflt16)`

(If I am getting off topic for a GitHub Issue, please point me to a forum where you would like to see this discussion).

**Comment by peolivei2** [comment]
The payload in your logs seem correct. Can you post it in JSON format so we can inspect it better (` context.log(JSON.stringify(req.body))` after your transformation).

I'm not sure what could be the reason for the error in your logs. Can you try restarting the Function App?
Searching a bit, this error can be emitted by the calls to `update` in lines 171 or 185 of `lib/engine.js` in your Function App. If restarting doesn't work, can you try inspecting the values of the parameters being passed to this calls? (just add a log before the calls, to make sure that the parameters are not undefined).

**Comment by coastalplain** [comment]
Thank you.  I inserted `context.log()` in a few places and restart frequently when code changes.  Within index.js on approximately line 20 on the first line within module.exports
```javascript
    module.exports = async function (context, req) {
    context.log(JSON.stringify(req.body));
    try {
```
and in lib/engine.js in the async functions.  

```javascript
async function getDeviceKey(context, deviceId) {
    if (deviceCache[deviceId] && deviceCache[deviceId].deviceKey) {
        return deviceCache[deviceId].deviceKey;
    }
    context.log('Within engine.js, async function getDeviceKey');
    context.log(JSON.stringify(context, deviceId));
    const key = crypto.createHmac('SHA256', Buffer.from(await context.getSecret(context, context.primaryKeyUrl), 'base64'))
        .update(deviceId)
        .digest()
        .toString('base64');
    context.log('AFTER  const key =')
    context.log(JSON.stringify(key));
    context.log('Just before deviceCache[deviceID].deviceKey = key in engine.js');
    deviceCache[deviceId].deviceKey = key;
    context.log(JSON.stringify(key));
    context.log('END of async function getDeviceKey');
    return key;
```
Is it that the [ERROR] may be caused in creating the const key within async function getDeviceKey(context, deviceId)?   Here is the [context.log](https://github.com/Azure/iotc-device-bridge/files/2914470/context.log)  for approximately 6 uplinks from the one Device (I've inserted spaces after each `[Information] Executed 'Functions.IoTCIntegration' (Succeeded, Id=.` log entry and removed a block to help readability).

The TTN Console with times for the uplinks in case it helps someone in the future with latency from uplink to IoTCIntegration:
![image](https://user-images.githubusercontent.com/8905768/53556965-f6f1c280-3b12-11e9-99cf-6be6d881c814.png)

**Comment by peolivei2** [comment]
Thanks for providing the logs. The code is calling `getDeviceKey` twice, as expected, once before and once after registration. The first call to `getDeviceKey` succeeds, but the second one fails.

In line 189 (of the original code) of `engine.js` you can see that we are saving the device key in a cache. So, the second call to `getDeviceKey` should be returning the cached key, in line 181. It doesn't return at that point and fails probably in the call to ` update` in line 185 of the original code. It looks like there's a problem with the `deviceId` that's being passed as argument to the second call of `getDeviceKey`. You added `context.log(JSON.stringify(context, deviceId))`, but unfortunately `JSON.stringify` only strigifies the first parameter, so we can't see what the value of `deviceId` was in the second call. Can you modify it to log the value of `deviceId` along the `getDeviceKey` call? In the original code, I can't find a reason why this value may be different between the first and second calls, but there may be something that I missed.

**Comment by coastalplain** [comment]
Here is the code for the last two functions in lib/engine.js (logfile below); if I missed where you needed the context.log(JSON.stringify...), please advise:

```javascript
async function getRegistrationSasToken(context, deviceId) {
    context.log('Within engine.js, async function getRegistrationSasToken');
    context.log(JSON.stringify(context, deviceId));
    const uri = encodeURIComponent(`${context.idScope}/registrations/${deviceId}`);
    const ttl = Math.round(Date.now() / 1000) + registrationSasTtl;
    const signature = crypto.createHmac('sha256', new Buffer(await getDeviceKey(context, deviceId), 'base64'))
        .update(`${uri}\n${ttl}`)
        .digest('base64');
context.log(JSON.stringify(uri, ttl, signature.update, signature.digest));
context.log('END of async function getRegistrationSasToken');

    return`SharedAccessSignature sr=${uri}&sig=${encodeURIComponent(signature)}&skn=registration&se=${ttl}`;
}

/**
 * Computes a derived device key using the primary key.
 */
async function getDeviceKey(context, deviceId) {
    context.log('Start within engine.js, async function getDeviceKey');
     if (deviceCache[deviceId] && deviceCache[deviceId].deviceKey) {
       context.log('next lines are deviceCache[deviceId], .deviceKey, deviceId, key')
        context.log(JSON.stringify(deviceCache[deviceId]));
        context.log(JSON.stringify(deviceCache[deviceId].deviceKey));
         context.log(' ----- end, before return within -> if (deviceCache[deviceId] && deviceCache[deviceId].deviceKey) {');
        context.log(' ');
        return deviceCache[deviceId].deviceKey;
    }
    context.log('Within engine.js, async function getDeviceKey, after -> if (deviceCache... ');
    context.log(JSON.stringify(context));
     const key = crypto.createHmac('SHA256', Buffer.from(await context.getSecret(context, context.primaryKeyUrl), 'base64'))
        .update(deviceId)
        .digest()
        .toString('base64');
    context.log('AFTER const key =; next lines are .deviceKey thencontext');
    context.log(JSON.stringify(deviceCache[deviceId].deviceKey));
    context.log(JSON.stringify(context));
    context.log('  -  ');
    
    context.log('Just before deviceCache[deviceID].deviceKey = key in engine.js');
    deviceCache[deviceId].deviceKey = key;
    context.log(JSON.stringify(key));
    context.log(JSON.stringify(context));
     context.log('END of async function getDeviceKey');
    context.log('---------------------------------');
    context.log(' ');
    return key;
context.log('**************************************************');
context.log('  ');
}
```
Here is the associated logfile (should I really be removing all the keys and such?):
[context2.log](https://github.com/Azure/iotc-device-bridge/files/2916881/context2.log)

**Comment by peolivei2** [comment]
Can you add `context.log(JSON.stringify(deviceId));` and `context.log(JSON.stringify(deviceCache));` right at the start of the `getDeviceKey` function? This will let us know the value of `deviceId` and the state of `deviceCache`.

If you share your `index.js` and `engine.js` files, I can replace them in one of my instances to test.

(please continue to remove the keys from the logs, as GitHub issues are publicly visible)

**Comment by coastalplain** [comment]
Thank you for all the help--I've added  deviceId an deviceCache to the start as you requested.  The log is attached  [context3.log](https://github.com/Azure/iotc-device-bridge/files/2917631/context3.log).  

> index.js and ./lib/index.js
>
Attached are files for js and logs--thank you for all the insight!

```javascript
/**
 * Computes a derived device key using the primary key.
 */
async function getDeviceKey(context, deviceId) {
    context.log('Start within engine.js, async function getDeviceKey');
    context.log(JSON.stringify(deviceId)); 
    context.log(JSON.stringify(deviceCache));
     if (deviceCache[deviceId] && deviceCache[deviceId].deviceKey) {
       context.log('next lines are deviceCache[deviceId], .deviceKey, deviceId, key')
        context.log(JSON.stringify(deviceCache[deviceId]));
        context.log(JSON.stringify(deviceCache[deviceId].deviceKey));
         context.log(' ----- end, before return within -> if (deviceCache[deviceId] && deviceCache[deviceId].deviceKey) {');
        context.log(' ');
        return deviceCache[deviceId].deviceKey;
    }
```

[index2.log](https://github.com/Azure/iotc-device-bridge/files/2917637/index2.log)
[engine.js.txt](https://github.com/Azure/iotc-device-bridge/files/2917641/engine.js.txt)
[index.js.txt](https://github.com/Azure/iotc-device-bridge/files/2917645/index.js.txt)

**Comment by peolivei2** [comment]
Found the problem: at line 87 of your ` engine.js`  file you have `const deviceId = device.device;`. That line should actually be `const deviceId = device.deviceId;` . Replacing it fixes the problem.

**Comment by coastalplain** [comment]
Thank you @peolivei2 for all you help!   So simple.   I’m not sure how that was changed, as I was not working in that part of the code—but obviously I must have changed it.
