### ISSUE TITLE
Question: Has anyone been able to use azure stream analytic to trigger the device bridge function? 

### ISSUE THREAD

**Issue by Grewall** [Azure/iotc-device-bridge#20]

**Comment by peolivei2** [comment]
We haven't performed this specific test yet, but device-bridge is in essence an HTTP triggered JavaScript Azure Function. [This doc](https://docs.microsoft.com/en-us/azure/stream-analytics/stream-analytics-with-azure-functions) describes how to trigger an Azure Function from Azure Stream Analytics, but the examples are for C# functions, You have to check it the same setup can be used with JavaScript functions.
