### ISSUE TITLE
Error in the index.js of Function App

### ISSUE THREAD

**Issue by Moh-Bharti** [Azure/iotc-device-bridge#22]
I am trying to run the index.js file but got the following error as I explicitly mentioned the device id in the correct format-
 [ERROR] Cannot read property 'payload_fields' of undefined
If I used req.body.dev_id in the deviceId field I got the error-
 [ERROR] Cannot read property 'dev_id' of undefined

**Comment by firedog1024** [comment]
In index.js can you add the line:

context.log(JSON.stringify(req.body));

before line 21:

await handleMessage({ ...parameters, log: context.log, getSecret: getKeyVaultSecret }, req.body.device, req.body.measurements, req.body.timestamp);

Then reply back with the output in the console window.  I suspect that the payload of the webhook POST is not in the correct format for the code in index.js to parse and that is causing the error.  The index.js expects that the incoming body looks something like this example:

{
    "device": {
        "deviceId": "my-cloud-device"
    },
    "measurements": {
        "temp": 20.31,
        "pressure": 50,
        "humidity": 8.5,
        "ledColor": "blue"
    }
}

If it does not have this format then you need to adjust the code in index.js to get the deviceid and measurements into the correct format or adjust the parameters into handleMessage.

**Comment by Moh-Bharti** [comment]
here is the data format as mentioned above which I got in ttn data-
{
  "device": {
    "deviceId": "****7bd-7451-4f0f-a5a6-*********"
  },
  "measurements": {
    "humidity": 34819,
    "ledColor": "blue",
    "pressure": 977168130,
    "temperature": 0
  }
}

As with the index.js file I got the following same error even though I have hardcoded the device ID-


[Information] undefined
[Information] [ERROR] Cannot read property 'payload_fields' of undefined
 Even though I have written same code as given here in index.js file.

I got the following line of output after writing the log output function -

2019-06-06T04:41:58.323 [Information] {"app_id":"test_dragino_*****","dev_id":"****ba7bd-7451-4f0f-a5a6-2748******","hardware_serial":"1234567801234567","port":1,"counter":252,"payload_raw":"BWf7CgJnPcIDiARbAgvKbgBY3g==","payload_fields":{"device":{"deviceId":"006ba7bd-7451-4f0f-a5a6-27486d609b36"},"measurements":{"humidity":34819,"ledColor":"blue","pressure":-1111320322,"temperature":0}},"metadata":{"time":"2019-06-06T04:41:57.583424054Z","frequency":868100000,"modulation":"LORA","data_rate":"SF7BW125","coding_rate":"4/5","gateways":[{"gtw_id":"eui-a840411b1b38ffff","timestamp":1434524049,"time":"2019-06-06T04:41:57.477704Z","channel":7,"rssi":-48,"snr":7.8,"rf_chain":0,"latitude":28.542242,"longitude":77.26924,"location_source":"registry"}]},"downlink_url":"https://integrations.thethingsnetwork.org/ttn-eu/api/v2/down/test_dragino_water/water-monitor?key=ttn-account-v2.ecchJxCyQmpzZUkxuxSeEmDOsdScA3RdfJuUmCiT0Zw"}
2019-06-06T04:41:58.323 [Information] [ERROR] Invalid format: invalid measurement list.

**All things are fine as you said so why giving the same error-**

**Comment by Moh-Bharti** [comment]
If you try to run this website [https://iotc-fnr6o3jezim6lpo.azurewebsites.net/api/IoTCIntegration](url),
You will see the error.

**Comment by firedog1024** [comment]
The incoming POST body data is as follows:

{  
   "app_id":"test_dragino_***",
   "dev_id":"ba7bd-7451-4f0f-a5a6-2748",
   "hardware_serial":"1234567801234567",
   "port":1,
   "counter":252,
   "payload_raw":"BWf7CgJnPcIDiARbAgvKbgBY3g==",
   "payload_fields":{  
      "device":{  
         "deviceId":"006ba7bd-7451-4f0f-a5a6-27486d609b36"
      },
      "measurements":{  
         "humidity":34819,
         "ledColor":"blue",
         "pressure":-1111320322,
         "temperature":0
      }
   },
   "metadata":{  
      "time":"2019-06-06T04:41:57.583424054Z",
      "frequency":868100000,
      "modulation":"LORA",
      "data_rate":"SF7BW125",
      "coding_rate":"4/5",
      "gateways":[  
         {  
            "gtw_id":"eui-a840411b1b38ffff",
            "timestamp":1434524049,
            "time":"2019-06-06T04:41:57.477704Z",
            "channel":7,
            "rssi":-48,
            "snr":7.8,
            "rf_chain":0,
            "latitude":28.542242,
            "longitude":77.26924,
            "location_source":"registry"
         }
      ]
   },
   "downlink_url":"https://integrations.thethingsnetwork.org/ttn-eu/api/v2/down/test_dragino_water/water-monitor?key=ttn-account-v2.ecchJxCyQmpzZUkxuxSeEmDOsdScA3RdfJuUmCiT0Zw"
}

Note that the device nand measurements are in the "payload_fields" object and not at the root of the JSON.  In the index.js code the line 21:

`await handleMessage({ ...parameters, log: context.log, getSecret: getKeyVaultSecret }, req.body.device, req.body.measurements, req.body.timestamp);`

is expecting to find device and measurements at the root so we need to adjust it so it is looking in the "payload_fields" object.  Change line 21 in index.js to:

`await handleMessage({ ...parameters, log: context.log, getSecret: getKeyVaultSecret }, req.body.payload_fields.device, req.body.payload_fields.measurements, req.body.timestamp);`

Hopefully this should now work correctly for you.
