### ISSUE TITLE
Integration with IoT Hub?

### ISSUE THREAD

**Issue by terrymandin** [Azure/iotc-device-bridge#23]
This is more of a feature request. :)

I have come across similar scenarios where customers want a bridge from a device maker's cloud to the IoT Hub.  Have you given any consideration to expanding the functionality to bridge to the IoT Hub as well?

**Comment by peolivei2** [comment]
While the project is meant to connect devices to Azure IoT Central, after deploying you can adapt the code to connect devices just to IoT Hub. The main difference is that the code here gets the Hub connection string from DPS. This step could be skipped in this case.
