### ISSUE TITLE
Change Device Property via Azure Function

### ISSUE THREAD

**Issue by drunkdev1991** [Azure/iotc-device-bridge#24]
Hello everybody,

I am trying to get my SigFox location tracking devices (GPS) to Azure IoT Central. I would like to use the Maps functionality of the dashboard to visualize the location of my devices. Therefore I need to change the device property continiously.

I have been trying to follow this instruction:
https://docs.microsoft.com/en-us/azure/iot-central/howto-connect-nodejs#add-a-real-device

I believed the Azure Function is simulating a device and uses the SigFox payload as a input for telemetry, event and/or state. So I tried to expand the engine.js as described above (url), but it lead me there to understand, that the device twin is not callable via http - known issue here:
https://github.com/Azure/azure-iot-sdk-node/issues/351

Is is possible to expand the engine.js so, that I do not need to use the device twin here?

I also tried to use MS Flow but it did not end well either.

Are there any further possibilities? Thank you very much! 
Cheers
DD

**Comment by kartben** [comment]
Please have a look at https://github.com/kartben/iotc-device-bridge/blob/properties-support/IoTCIntegration/lib/engine.js for an example of how to do this. Then just add "properties" in your POST payload in addition to "measurements" and that should work :-)

**Comment by kartben** [comment]
Note that this is indeed using MQTT instead of HTTP to address the limitation you mentioned in your initial comment, and this hasn't been fully tested, so please use this as a starting point :-)

**Comment by Danorexic** [comment]
Microsoft late last night posted an update where they've added an official location telemetry field which offers real time and historical data points, just like the other telemetry fields. The update is detailed here: https://docs.microsoft.com/en-us/azure/iot-central/howto-set-up-template#measurements

I cannot for the life of me get it to work. They don't really provide much detail or documentation beyond Screenshots of the dashboard and a Javascript snippet:

```
assetloc: {
  lon: floating point number,
  lat: floating point number,
  alt?: floating point number
}

```
I push data formatted with json from a Particle Dev board and it works fine for all the other fields, but not their new location telemetry. I tried sending it to lat, lon, assetloc. Tried sending a joined set of coordinates to assetloc. Tried nesting the lat and lon fields within the assstloc key in my json and had no luck getting any of it to post. 

I think when I tried nesting the data, the bridge wouldn't even connect to Azure properly and failed with error code 400.

Any comments on how push data to the new fields? Is this something the bridge would need to be updated to support?

**Comment by drunkdev1991** [comment]
@kartben Thank you for the hint! Indeed I tried it the way you presented, it is nice, but not working yet correctly due to the device twin properties. It was pain in the *** tbh. I would recommend not to do it like that, since Microsoft seems to implement this feature by themselves as @Danorexic mentions.
So we have been working cutting edge - thats nice! :)

Furthermore I tried that feature, which is not properly working now and it is leading to an error. The Map is not displayed yet. I am really looking forward, since that is going to be fixed soon!

**Comment by kartben** [comment]
@Danorexic @drunkdev1991 If you want to send location as telemetry, you first need to make sure you've declared a telemetry field in your template of type "location", say you name this field "loc" (it can be anything, really). Your measurement payload should then look something like the following:

```json
{
    "device": {
        "deviceId": "mangoh-bcabe"
    },
    "measurements": {
        "loc": {
            "lat": 12.345,
            "lon": 67.890
        }
    }
}
```

However, one important caveat is that the "loc" field is now causing the validation of the measurements to fail in the bridge (see: issue #25) so one short term fix suggestion is to simply remove the call to `validateMeasurements()` in your engine.js file until we deploy a proper fix :)

**Comment by Danorexic** [comment]
Confirming that the solution posted by @kartben works and I now have data points on the IoT Central location telemetry map. For anyone new to Azure stuff like me, to update your engine.js file, you go to your Azure portal, Function App, expand down and click on IoTCIntegration. It'll take a moment and initially open index.js. It's easy to miss but on the right hand side of that view, there's an option that says 'View files', click that and you'll be able to navigate to the lib folder and open engine.js. 

Commenting out lines 38-40 disabled the check and allowed my coordinates to push to IoT Central:
`    //if (!validateMeasurements(measurements)) {
    //    throw new StatusError('Invalid format: invalid measurement list.', 400);
    //}`

**Comment by drunkdev1991** [comment]
My function also provides similar results - it is opening the connection to the device in IoT Central, forwards the message and closes the connection successfully. The payload has same structure as @kartben described.
The data is not forwarded to IoT Central though, and no values are displayed.
Instead I get an unknown error with a error code. I forwarded that to the MS Support.
Additionally the Dashboard of my device template is somehow corrupted, if i want to change or delete existing elements, the tiles are magically moving away below my mouse pointer...
This is obviously not an issue with the function itself, but maybe someone is experiencing the same problems?
