### ISSUE TITLE
The Things Network code update + Send to database

### ISSUE THREAD

**Issue by KenSense** [Azure/iotc-device-bridge#27]
```
req.body = {
    device: {
        deviceId: req.body.hardware_serial
    },
    measurements: req.body.payload_fields
};
```

Should be replaced with:
```
req.body = {
    device: {
        deviceId: req.body.hardware_serial.toLowerCase()
    },
    measurements: req.body.payload_fields
};
```

How can I send the data with this i/o bridge also to an azure database?
IoT Central has this easy export option but it averages my data points to new 1 min average data points. 

I want to log my original IoT data not the averaged data!

**Comment by peolivei2** [comment]
Thanks for the feedback on the first issue. I've sent a change to update the docs.

For the second one, the Continuous Data Export feature in IoT Central creates export files with a minute timestamp in the name, but the file will contain all measurements for the period, i.e., the points are **not** averaged.

**Comment by KenSense** [comment]
> For the second one, the Continuous Data Export feature in IoT Central creates export files with a minute timestamp in the name, but the file will contain all measurements for the period, i.e., the points are **not** 

You are right, I did some more testing and also removed the simulated device from IoT central an it looks to be correct, would be better if the IoTCentral UI graph shows like up to 500 point (Excel doesn't have a hard time with 500 points)
Screenshot with the different data points (based on IoT central table view and added extra rows in excel), the empty column is strange, why is it there? Why not have headers with a timestamp instead of a time period (I didn't choose the period).
<img width="836" alt="DataBlob" src="https://user-images.githubusercontent.com/49442805/61284441-43d2ee80-a7bf-11e9-9870-aa67b5c7ca70.png">

Is there an easy way to query/see blob data in table format?

**Comment by viv-liu** [comment]
@KenSense Do you want to see this data in table format for user consumption or do you have a downstream service that consumes tabular data?

Do you only want to view/query a minute's worth of data in table format?
 
Right now the only supported type of export is in Avro format and there isn't an easy way to change that to display or be queried in table format.

**Comment by KenSense** [comment]
It's not for user consumption I would just like to make a graph of all the data that was logged.
(a real graph not like IoT Central)
or just query at which times certain conditions were true.

Seems like a lot of overhead to get the logged data.
