### ISSUE TITLE
Devices are registered using only TTN device ID and not application ID

### ISSUE THREAD

**Issue by ohjohnsen** [Azure/iotc-device-bridge#31]
In TTN I register applications by device type (e.g. "temperature-sensor-a" and give them device ID "nodeN" ("node1", "node2" etc.).  The same goes for another application with a different device type.  But devices is registered only by device ID in Azure IoTC, so there is a conflict of multiple applications have devices registered with the same device ID (the data points will be merged into the same device in Azure IoTC).

I propose that the device bridge registers devices by combining the application ID and device ID (e.g. "temperature-sensor-a-node1").  This way you will have a fully unique device name in Azure IoTC.

**Comment by peolivei2** [comment]
After deploying the solution, you can modify the code in the Azure Function to generate a device Id in a way that's more convenient for your application. For instance, in this case you can modify the code to combine the application Id and device Id.

**Comment by ohjohnsen** [comment]
Yes, for sure.  But don't you agree that this is an issue that should be addressed?  I mean, TTN allows for devices in two different applications to have the same device ID.  The IoTC device bridge should support this also.

**Comment by peolivei2** [comment]
The sample that we present in the README simply provides a simple and fast way to connect a single TTN application to a single IoT Central application (the sample is not actually deployed to the solution). The sample uses `hardware_serial` field as the device Id to guarantee that it meets the appropriate format and to make it easier identify and join the data later on in case you have features like Continuous Data Export turned on, as this same Id will be used in the exported data.

For these reasons, if you need the `app_id` or other TTN fields to be included, you can easily modify the provided sample, making sure that the fields, if used in the device Id, meet the restrictions explained in the README (alphanumeric, lowercase, and may contain hyphens).

**Comment by ohjohnsen** [comment]
Yes, you are absolutely correct.  I'm closing this issue.
