### ISSUE TITLE
During npm install, a message regarding 'Invalid value for encodingHint' is shown

### ISSUE THREAD

**Issue by sandervandevelde** [Azure/iotc-device-bridge#32]
Is this harmless?

![image](https://user-images.githubusercontent.com/694737/67145275-70941780-f280-11e9-857d-a1ae20f85d1c.png)

The actual text:

```
function(t){if(void 0===t&&(t="legacy"),this._body instanceof b)return this._body.toString();if(this._body instanceof ArrayBuffer)switch(t){case"legacy":return String.fromCharCode.apply(null,new Uint16Array(this._body));case"iso-8859":return String.fromCharCode.apply(null,new Uint8Array(this._body));default:throw new Error("Invalid value for encodingHint: "+t)}return null==this._body?"":"object"==typeof this._body?JSON.stringify(this._body,null,2):this._body.toString()}
```

I ran the same 'npm install' command a second time, this time all went well:

![image](https://user-images.githubusercontent.com/694737/67145337-20698500-f281-11e9-9756-2197b2341166.png)

**Comment by peolivei2** [comment]
As the command finished after running a second time, it should be fine.

**Comment by sandervandevelde** [comment]
OK. Thanks for the follow-up.

**Comment by CarterBland** [comment]
I'm seeing this while I run webpack, more specifcally npm run prod on laravel... doesn't seem to actually run the command fully.

**Comment by peolivei2** [comment]
How is this related to this repository?
