### ISSUE TITLE
Device bridge don't work with Azure IoT Central Preview

### ISSUE THREAD

**Issue by rploeg** [Azure/iotc-device-bridge#34]
I have connected the device bridge to the preview version of Azure IoT Central. The preview version expects a device template in the request.

**Comment by peolivei2** [comment]
What error are you seeing specifically? The device-bridge should work for preview applications in the same manner that it works for legacy ones, i.e., (i) devices created through device-bridge show up under the "All devices" section of the Devices page, where you can use the "Migrate" function to move it to the correct template, or (ii) you can create the device in the correct template ahead of time and then send data for it using device-bridge.

**Comment by rploeg** [comment]
I get this error :

2019-12-23T12:50:53.876 [Information] [ERROR] Invalid format: a device specification must be provided.

When I cannot it to the 'old' IoT Central it works directly.

**Comment by peolivei2** [comment]
Thank you for the info. This error is not related to the application type. It means that [the "device" field is not being provided in the payload](https://github.com/Azure/iotc-device-bridge/blob/07527a4a17dc64db0003dd0f542e13ed300b446b/IoTCIntegration/lib/engine.js#L35) for device-bridge. What payload format are you using? We expect the payload to follow the format of the example below:

```json
{
    "device": {
        "deviceId": "my-cloud-device"
    },
    "measurements": {
        "temp": 20.31,
        "pressure": 50,
        "humidity": 8.5,
        "ledColor": "blue"
    }
}
```

**Comment by rploeg** [comment]
Thanks! Strange, I just post the same JSON and now it's working.....
