### ISSUE TITLE
Unable to send telemetry for device ******: Could not send message: Not Found

### ISSUE THREAD

**Issue by MateRadz** [Azure/iotc-device-bridge#37]
Hi,

Followed the readme for deployment and implementation and when submitting the payload through Test feature on functions portal, I get the error as above. What maybe the cause of this issue? (The device successfully registers in Azure IOT Central as it is seen on device list, but no test telemetry goes through.

**Comment by peolivei2** [comment]
Hi,

We can try a few things to get more info on why you're seeing this error:

1. Can you add some more debug logs to your Azure Function? For instance, in [line 64 of lib/engine.js](https://github.com/Azure/iotc-device-bridge/blob/master/IoTCIntegration/lib/engine.js#L64), can you print the entire error by adding `console.log('Error:', JSON.stringify(e));`. If for some reason this doesn't work, can you try adding `console.log('Error:', e.name, e.code);` (you'll need to restart the function app after making the change) (also, please redact any sensitive info before pasting the output here).
2. Is this happening for every device that you try? Can you try changing the device Id in the payload to see if you still get the same error.
3. Is the device associated to a template in IoT Central or is it still unassociated? If the latter, can you associate it to a template before trying again.

Hopefully we can get enough info to understand the problem better.

**Comment by MateRadz** [comment]
Hi,

Thanks for insight on error codes. I guess you could include such extended logging of errors in the next release. In my case magically I no longer have the issue (took some 2 hours of function running) plus maybe I was playing with "migrate" of the device in IOT Central. 
In my case I am using this function as output to Azure Stream Analytics to bridge it with telemetry coming to IOT Hub (to utilise benefits of both PaaS and SaaS IOT offerings of Azure)  - I had to modify it anyway so it accepts array of telemetry messages from different devices.
I also had to "Lower Case" the device IDs (strangely IOT Hub accepts them while IOT Central does not).
