### ISSUE TITLE
Device ID regex should be updated

### ISSUE THREAD

**Issue by kartben** [Azure/iotc-device-bridge#38]
ex. DEVICE001 triggers: "Invalid format: deviceId must be alphanumeric, lowercase, and may contain hyphens."

Naming restrictions for DPS registration IDs have been relaxed a while ago, and are now: "The registration ID is alphanumeric, case insensitive, and may contain special characters including colon, period, underscore and hyphen."

**Comment by peolivei2** [comment]
IoT Central has a special character restriction. I'll update the code to accept underscore and upper case, though.
