### ISSUE TITLE
missing request-promise-native dependency

### ISSUE THREAD

**Issue by rayozzie** [Azure/iotc-device-bridge#41]
Hello.  I am trying to help a customer get their data into iotc, and this looks to be quite promising.

However, when I followed instructions, after the 'npm install', it still could not start because:

 “Error: Cannot find module 'request-promise-native’”,

I did “npm install request-promise-native” and all seemed to be fine, but I though you would want to know so you can fix this.

thx.

**Comment by peolivei2** [comment]
It might have been that the function runtime took a while to restart and recognize the newly installed packages. `request-promise-native` is already included in the [package.json](https://github.com/Azure/iotc-device-bridge/blob/72708b16562cd25be731a6d33d89706f895fefc9/IoTCIntegration/package.json#L11), so if the `npm install` command succeeded it should be present after the function was restarted.
