### ISSUE TITLE
First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.

### ISSUE THREAD

**Issue by Jcardif** [Azure/iotc-device-bridge#42]
Every time i call the function from SigFox and event when i test it with postman, i get an error message that First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.

**Comment by peolivei2** [comment]
We'd need some more info to be able to investigate:
1. Can you provide the payload that you're sending through Postman (please remove any secrets and sensitive information)?
2. Can you post the entire error that you're getting back (HTTP response status and response body).
3. When sending the request, go to the Azure Function page (same page where you obtained the function URL). Click on `Console` and check what error will be printed. This error will likely contain a stack trace, which will be helpful to identify exactly where it's failing.
4. Also, have you made any changes to the original function code after deploying? (for instance, adding the code to handle SigFox payloads)

**Comment by Jcardif** [comment]
**The payload sent from sigfox is**
`{
    "device": {
        "deviceId": "my-cloud-device"
    },
    "measurements": {
        "temp": 20.31,
        "pressure": 50,
        "humidity": 8.5,
        "ledColor": "blue"
    }
}`
**The Entire error and HTTP response status is as in the screenshot below**
![image](https://user-images.githubusercontent.com/29174946/76153132-d0c51200-60d8-11ea-8f1e-9e108e4d1ca0.png)

**here are the logs when i make the request**
![image](https://user-images.githubusercontent.com/29174946/76153178-737d9080-60d9-11ea-9115-bcfbb5127f5c.png)

**I made changes to the original source function as below:**

```
module.exports = async function (context, req) {
    try {
        const payloadDefinition = 'gforce::uint:8 lat::uint:8 lon::uint:16'; 

        req.body = {
            device: {
            deviceId: req.body.device.toString()},
            measurements: require('./converters/sigfox')(payloadDefinition, req.body.data)
        };
        await handleMessage({ ...parameters, log: context.log, getSecret: getKeyVaultSecret }, req.body.device.toString(), req.body.measurements, req.body.timestamp);
        context.res = {
            status: 204
        };
    } catch (e) {
        context.log('[ERROR]', e.message);

        context.res = {
            status: e.statusCode ? e.statusCode : 500,
            body: e.message
        };
    }
}
```

**Comment by peolivei2** [comment]
Thanks for the detailed data. You added the code to handle SigFox payloads, butt he body that you're sending doesn't match the data that is sent by a SigFox integration. The payload sent from the SigFox cloud contains a `device` field with the device Id and a `data` field, which contains the HEX encoded data sent by a device. This data is described by a format string that represents how it should be decoded (`payloadDefinition` variable in the code you posted).

If you wish to test the payload that you're currently sending, you need to remove the code that handles SigFox payloads.
