### ISSUE TITLE
Format TTN to Azure (ESP32)

### ISSUE THREAD

**Issue by Meister1410** [Azure/iotc-device-bridge#44]
Hey,
 I´ve tried to sent data from a Heltec ESP32 Wifi OLED 32V2 over a Raspberry PI Gateway to TTN. Example: https://github.com/HelTecAutomation/ESP32_LoRaWAN 
The next step is to send this Data to Azure IOT Central. Can I use the same Decoder in this example? 
At 5. there is an example of the format that azure need to understand. Is this format before or after the decoder from ttn? At this time we have Issus to send real data to TTN. But if we creat this in the wrong format it´s useless for our projekt.

**Comment by peolivei2** [comment]
The decoder function needs to be specific for the data that your device sends. The decoder provided in the README is a example for a device that is sending a float, an int32, and a short.

As for the format, the decoder function needs to be in the TTN side and it's used to fill the `payload_fields` field sent by TTN. After that, [the second snippet of code that the README asks you to insert](https://github.com/Azure/iotc-device-bridge#example-3-connecting-devices-from-the-things-network-through-the-device-bridge) in `IoTCIntergration/index/js` will convert the payload that comes from TTN to the format that's shown in step 5 of the instructions.
