### ISSUE TITLE
Change IoT Central

### ISSUE THREAD

**Issue by sihbher** [Azure/iotc-device-bridge#47]
Is there a way to change the IoT Central data (scope, secret) after deploy it? how would it be?

**Comment by peolivei2** [comment]
Thought the easiest way to change it would be creating a new instance pointing to the correct Azure IoT Central application, you can change it following these steps:

#### Updating the key:
- There will be a KeyVault deployed to the same resource group as the Function App. Navigate to the Key Vault, then `Access policies` and add yourself to the access list so you can access the secrets (remember to save the changes after adding it).
- Go to the `Secrets` section and then click the secret that has the key. Click on `New version`, then in `Value` insert the new key and save.

#### Updating the scope Id:
- In the Function App, go to `Application settings`
- Find the setting named `SCOPE_ID` and edits it's value to the new Scope Id, then save.
- Restart the Function App to refresh the key and setting.

If all goes well, the instance will now point to the new application.

**Comment by sihbher** [comment]
Thanks for you answer @peolivei2 , I only think that would be goo if there were a easy way to switch it, I am thinking for example when you first deploy it to dev environment and then you want to move it into prod.

**Comment by peolivei2** [comment]
One option is to automate these operations using az cli commands. For reference, check the [az keyvault commands](https://docs.microsoft.com/en-us/cli/azure/keyvault?view=azure-cli-latest) and [az functionapp](https://docs.microsoft.com/en-us/cli/azure/functionapp?view=azure-cli-latest) commands.
