### ISSUE TITLE
Documentation: Description of the payload to send to IOTC Device Bridge

### ISSUE THREAD

**Issue by askpatrickw** [Azure/iotc-device-bridge#49]
Firstr off, this all works great and thank you for support the community with it. It is very helpful!

As I was setting this up I found the section about the payload to be send to be confusing. This is the section I'm referring to:

> Messages sent to the device bridge must have the following format in the body:
> 
> ```jason
> {
>     "device": {
>         "deviceId": "my-cloud-device"
>     },
>     "measurements": {
>         "temp": 20.31,
>         "pressure": 50,
>         "humidity": 8.5,
>         "ledColor": "blue"
>     }
> }```
> 
> An optional timestamp field can be included in the body, to specify the UTC date and time of the message. This field must be in ISO format (e.g., YYYY-MM-DDTHH:mm:ss.sssZ). If timestamp is not provided, the current date and time will be used.

I thought one of two things after reading it:
1. This solution is a hardcoded example for a specific device template which has a measurements interface that has temp, pressure, humidity, ledColor capabilities.

OR 

2. Measurements is a JSON object within which you send the Interface object and their capabilities. For example given a "pump" interface with a "rate" telemetry capability and a "valve" interface with a "state" capability you would send:

```json
...
    "measurements": {
        "pump": {
            "rate": 7
        },
        "valve": {
            "state": "open"
        }
     }
```

I was hopeful the first one wasn't true and tried the second approach which did not work. Through testing, I determined that "Measurements" is a payload object sent to the IOTC Device Bridge which contains a flat list of capabilities with no reference to the interface to which the capabilities belong. So in my pump example, you would send:

```json
...
    "measurements": {
        "rate": 7,
        "state": "open"
     }
```

I tried this and it works, but can you confirm this is indeed what we should expect?

I also tried creating two Interfaces with identically named Capabilities and the Device Templates UI allows this. How does the IOTC Device bridge handle this?

I'm happy to do a PR for the README if you can help me understand those cases. Thank you!

**Comment by peolivei2** [comment]
As your conclusion described, `measurements` should be a flat object with capabilities. device-bridge still doesn't have support for interfaces (that will come in a future version). Just like with the currently available device SDKs, if you send the value for a capability with the same name that is present in two different interfaces, the measurements will show up in both capabilities.

**Comment by askpatrickw** [comment]
Thanks, I didn't know the Device SDKs also worked that way as well. That's good info. I'll make a circle back with a suggestion for the README in a couple days...

**Comment by askpatrickw** [comment]
Here's a suggestion on an update to the README. If you're happy with it... I'll submit a PR.

-----

    Messages sent to the device bridge must have the following format in the body:
```json
    {
        "device": {
            "deviceId": "my-cloud-device"
        },
        "measurements": {
            "temp": 20.31,
            "pressure": 50,
            "humidity": 8.5,
            "ledColor": "blue"
        }
    }```

The properties of the measurements object must each match a capability in the
IOT Central device template for this device. 

> NOTE: The IOTC Bridge is not currently aware of the full device Template hierarchy.
If a message has a value for a capability with a name that is present in two different
interfaces, the measurements will show up in both capabilities. To minimize confusion,
it is suggested your device template capability names are unique across your entire
device template and not
just with an interface.

An optional timestamp field can be included in the body, to specify the UTC date and
time of the message. This field must be in ISO format
(e.g., YYYY-MM-DDTHH:mm:ss.sssZ). If timestamp is not provided, the current date
and time will be used. When using timestamp the body of the message must look
like this:

```json
    {
        "device": {
            "deviceId": "my-cloud-device"
        },
        "measurements": {
            "temp": 20.31,
            "pressure": 50,
            "humidity": 8.5,
            "ledColor": "blue"
        },
        "timestamp": "2020-01-25T20:40:58.285Z"
    }```

--------

**Comment by peolivei2** [comment]
There are some other changes that we'll need to include to the README in our end (changes to naming, other application types, etc.). I'm preparing a PR to address this and other scenarios. I'll send it towards the end of the week.

**Comment by askpatrickw** [comment]
Feel free to copy and paste my ideas, make them your own, etc... As long as the next person has an easier time is all I'm hoping to achieve with my suggestions.
