### ISSUE TITLE
Internal Server Error after deployment (after Console moved)...

### ISSUE THREAD

**Issue by topese** [Azure/iotc-device-bridge#51]
I have deployed the Device Bridge a number of times the old way via the Console under the actual Function previously. When I tried again today it took me some time to actually realize that the Console UI piece had been moved (learned that in here).

When I deploy the function as stated in the updated README (thanks for swiftly doing that by the way), everything seems to deploy just fine. When I do the step >> npm install I get a some WARNs that I haven't seen in previous deployments. The npm install returns almost immediately as well, much quicker than before and in much less than the stated 20 minutes or so. It makes me think there is something awry.

![Screen Shot 2020-06-17 at 03 00 04](https://user-images.githubusercontent.com/29483057/84886360-9e8e5d80-b094-11ea-8518-7d5a16cc9235.png)

When I try to post some JSON data to the URL I get a 500 Internal Server Error back for all messages. I did try a "simply formatted" message just to make sure. Trying from Postman yields the same 500 HTTP status code.

Is there possibly an issue with the used deploy script or something that is not working as before?

**Comment by juliuszsielski** [comment]
I have the same issue, but this is the first time I am using this templete. Any help?

**Comment by peolivei2** [comment]
Sorry, there's a small problem in the README for this section. Once you get to the console, before running the install command, you should enter the function directory by entering the command: `cd IoTCIntegration`, as in the image below:

![image](https://user-images.githubusercontent.com/41344967/84928058-a47b4300-b082-11ea-99ef-3589c5fda6b8.png)

I'll send a PR shortly to correct the README.

**Comment by peolivei2** [comment]
The README fixes have been addressed in pull request #52

**Comment by topese** [comment]
Excellent, that did the trick alright. Thanks!
