### ISSUE TITLE
What is Storage Account responsible for?

### ISSUE THREAD

**Issue by juliuszsielski** [Azure/iotc-device-bridge#57]
Why the Storage Account is being created in ARM template? What is it responsible for in this example?

**Comment by kartben** [comment]
It's needed by the Azure Function that's in charge of the bridging, e.g. to store the various file that make up the function code.
See https://docs.microsoft.com/en-us/azure/azure-functions/storage-considerations

**Comment by juliuszsielski** [comment]
Oh, ok. So if I have consumption plan choosen, I am only paying for every function execution, key valut request and IoT Central message? There is no cost for storage account?

**Comment by peolivei2** [comment]
The storage account will be deployed to your subscription just like the Function App and the Key Vault.
Pricing details for storage can be found at: https://azure.microsoft.com/en-us/pricing/details/storage/
