### ISSUE TITLE
Time stamp not recognised

### ISSUE THREAD

**Issue by bamajeed** [Azure/iotc-device-bridge#60]
Hi, I followed the instruction for the message payload. The problem is that the timestamp is not being recognised. Any advice? The time stamp is in the past as data is loaded from a file.
{
  "device": {
    "deviceId": "log1"
  },
  "measurements": {
    "lbs": 0,
    "Weight_lbs": 4420,
    "Value": 195961
  },
  "timestamp": "2020-09-17T09:50:02.052Z"
}

**Comment by peolivei2** [comment]
By not recognized do you mean you're receiving a validation error from the bridge while trying to send it or that it's not behaving as expected in the IoT Central application?
In IoT Central this timestamp will be used for features like the chart visualization and will also be included when you export your data. In the "Raw data" view, however, the timestamp displayed is the time the message arrived in IoT Central.

**Comment by bamajeed** [comment]
Thanks @peolivei2 it was indeed the raw data view that confused me. this is fine now.

**Comment by bamajeed** [comment]
issue closed
