### ISSUE TITLE
Delay in matching the telemetry with the device template

### ISSUE THREAD

**Issue by bamajeed** [Azure/iotc-device-bridge#61]
Hi, I am seeing the issue where the telemetry data is not immediately modeled to the template. As seen in the attached screen shot the "data" was unmodeled for the first few data points.

![image](https://user-images.githubusercontent.com/38979131/93997816-b5c3a200-fd8b-11ea-8deb-04f0ef6b7bdd.png)

I used Postman with this payload 
{
  "device": {
    "deviceId": "iotcbridgetest"
  },
  "measurements": {
    "data": 22.0
  },
  "timestamp": "2020-09-22T01:11:43.43Z"
}

**Comment by peolivei2** [comment]
After a device is created, the model information takes a few minutes to update. During that time, data points will show up as unmodeled.

**Comment by bamajeed** [comment]
thanks @peolivei2 so is it a matter of time only? or does the device need to receive some telemetry messages before the modelling is done? In order not to miss any data points should we create a device first and wait some time before sending telemetry?

**Comment by peolivei2** [comment]
The delay is in relation to the time the device makes the first call to the provisioning service (DPS). This bridge does this call right before sending the data, to make the process transparent.

To ensure that the very first points will be modeled, you can send an initial message to the bridge for that device with an empty measurements section (`"measurements": {}`). This will generate a call to the provisioning service. After a a few minutes you should be able to send additional data and they should show up as modeled.

**Comment by bamajeed** [comment]
Thanks @peolivei2 for the clarification
