### ISSUE TITLE
how connect iot devices stimulation solution accelerator to IoT central through azure iot central device bridge ?

### ISSUE THREAD

**Issue by ahmed-assad** [Azure/iotc-device-bridge#63]
I create a devices simulation iot solution accelerators (as iot device ) and iot hub then azure iot central bridge to in final collect all simulated data to iot central ...
I have a problem in connect iot hub with bridge (azure functions) as an input .....

**Comment by peolivei2** [comment]
The device bridge is not directly compatible with the device simulation solution accelerator. The device simulation sends data to an IoT Hub, whereas the device bridge is intended to receive data through HTTP and send it to IoT Central.

The device simulation does not send data through HTTP, so you cannot connect it directly to the device bridge.
