### ISSUE TITLE
Sending messages to LoRa Devices

### ISSUE THREAD

**Issue by AnatoliiStepaniuk** [Azure/iotc-device-bridge#66]
Hello!
What is the recommended way to send messages to LoRa Devices from the application? (Downlinks)

Did not find this in the documentation. Please advice!

**Comment by peolivei2** [comment]
The code in this repo can only be used for upstream messages.
For downstream communication, we have a more complete project: https://github.com/iot-for-all/iotc-device-bridge
It offers way more flexibility and is extensible through containers.
