### ISSUE TITLE
The Things Network Bridge

### ISSUE THREAD

**Issue by Mircerson** [Azure/iotc-device-bridge#70]
Hi there,

I've been spending quite a lot of time figuring out how to get the TTN connected to the IoT Central.
For the authentification, I've used the Scope ID and the Primary key ( when I've created the Azure resource )
![image](https://user-images.githubusercontent.com/83925805/159053030-a2843fdd-3e3e-4a10-a646-11bff2fdac89.png)

I've made the following changes at line 21 in the js script:
![image](https://user-images.githubusercontent.com/83925805/159053351-518d521e-67c7-4470-a400-8427530b72a0.png)

Printing the data, I can see that I am getting the data I need by printing it to the console:
![image](https://user-images.githubusercontent.com/83925805/159053456-c6e65120-b45f-41af-a97b-d0da4adae693.png)

But the data does not get through to the Azure IoT Central:
![image](https://user-images.githubusercontent.com/83925805/159053524-4e2d41df-59c3-4645-b6be-340d89d3b21a.png)

Is this API still updated or has something changed from April?

Thanks.

**Comment by peolivei2** [comment]
The key in you image is a device key. For this solution, you need to use an application-level primary key (which can connect multiple devices). To get the application primary key, go to `Permissions > Device connection groups > SAS-IoT-Devices > Primary key`, as in the image below:

![image](https://user-images.githubusercontent.com/41344967/159078521-38aa93e7-d960-42e9-8141-568192ae67b3.png)

After getting this key, you will need to apply it to your device bridge instance. The easiest way to achieve this is redeploying solution. For an alternative way to update the key without redeploying, check this comment: https://github.com/Azure/iotc-device-bridge/issues/47#issuecomment-618067617

**Comment by Mircerson** [comment]
All sorted, thanks mate
![image](https://user-images.githubusercontent.com/83925805/159082642-5e1b3351-521f-4be9-a4f8-4a9e86d00d29.png)

**Comment by peolivei2** [comment]
Nice. Glad that it works.
