### ISSUE TITLE
Enter umodeled data with __t when telemetry is inside Component

### ISSUE THREAD

**Issue by SatriaPriambada** [Azure/iotc-device-bridge#71]
Hi Thanks for the great Bridge component!
My IoT Central is receiving the data successfully,
However when my telemetry is inside Component still it goes to unmodeled data column.

For example:
I used IoT Central template Temperature Controller
Then I tried to send request body 
```
{
  "device": {
    "deviceId": "temp-cont-bridge"
  },
  "measurements": {
     "thermostat2": {
        "temperature": 18.572516776817437
    },
      "__t": "c" 
  }
}
```
I expect the IoT Central to be able to recognize my component telemetry, but instead the response I got from IoT Central is
```

{
    "_eventcreationtime": "2022-03-23T19:24:46.78Z",
    "_unmodeleddata": {
        "thermostat2": {
            "temperature": 18.572516776817437
        },
        "__t": "c"
    },
    "_eventtype": "Telemetry",
    "_timestamp": "2022-03-23T20:43:11.965Z"
}
``` 
Is there something I'm missing or does this iotc-device-bridge component doesn't support sending telemetry inside Component?

Thanks and have a great day!

Other experiments:
I've also tried without __t and move __t position without success, with result such as 

- without __t 

```
{
    "_eventcreationtime": "2022-03-23T19:24:46.78Z",
    "_unmodeleddata": {
        "thermostat2": {
            "temperature": 18.572516776817437,
        }
    },
    "_eventtype": "Telemetry",
    "_timestamp": "2022-03-23T20:51:55.021Z"
}
```

- move __t inside Component Object

```
{
    "_eventcreationtime": "2022-03-23T19:24:46.78Z",
    "_unmodeleddata": {
        "thermostat2": {
            "temperature": 18.572516776817437,
            "__t": "c"
        }
    },
    "_eventtype": "Telemetry",
    "_timestamp": "2022-03-23T20:53:55.021Z"
}
```

**Comment by peolivei2** [comment]
This project doesn't have explicit support for components, but you can modify and redeploy a custom version to add it.

The message object is constructed in line 51 of [lib/engine.js](https://github.com/Azure/iotc-device-bridge/blob/00d920d8f7e08d37bdcebe661df6a5a40ad9f4b4/IoTCIntegration/lib/engine.js#L51)
You can specify the component by adding a special property to this message object in that line:
```javascript
message.properties.add("$.sub", componentName);
```
Where `componentName` is a variable containing the name of the component. You can then just send a regular message body without the component name:
```json
{
  "device": {
    "deviceId": "temp-cont-bridge"
  },
  "measurements": {
      "temperature": 18.572516776817437
  }
}
```

**Comment by SatriaPriambada** [comment]
Thank you so much for your help!
I'll try to change the code by adding $.sub and componentName and will get back to you soon!

**Comment by SatriaPriambada** [comment]
Hi I've tried your suggestion but sadly it seems to not help in recognizing Telemetry inside Component
This is the request I'm sending


`{"data":"{\"temperature\":28.572516776817437}","properties":{"propertyList":[{"key":"$.sub","value":"thermostat2"},{"key":"iothub-creation-time-utc","value":"2022-03-23T19:24:46.78Z"}]},"messageId":"","to":"","lockToken":"","correlationId":"","userId":"","contentEncoding":"utf-8","contentType":"application/json"}`

This is the output from the iot central raw data

```
{
    "_eventcreationtime": "2022-03-23T19:24:46.78Z",
    "_unmodeleddata": {
        "temperature": 28.572516776817437
    },
    "_eventtype": "Telemetry",
    "_timestamp": "2022-03-24T15:15:28.875Z"
}

```
This is the DTDL for the IoT Core [example Temperature Controller](https://github.com/Azure/iot-plugandplay-models/blob/main/dtmi/com/example/temperaturecontroller-2.json)

**Comment by peolivei2** [comment]
I did a quick check and it looks like the HTTP transport SDK that this project uses unfortunately does not support components :(
For components to work, the device must use a transport such as MQTT.
We have a similar project to this that is able to handle components if you want to try it: https://github.com/Azure/iot-central-bidirectional-device-bridge
The API is a bit different, but it offers the same functionality of being able to send the telemetry through HTTP.
